#!/bin/bash

# Exit silently if the graphics driver is not installed.
[[ ! -f /opt/nvidia/bin/nvidia-settings ]] && exit 0

name="vdpauinfo"
echo "building ${name}"

mkdir -p builddir && cd builddir || exit $?

builddir="${PWD}"
cleanup(){
cd "${builddir}" ; rm -fr "${name}" && echo -e "\nDirectory cleaned!";
}
trap cleanup EXIT

find . -type f -mtime +1 -exec rm -rf {} \;

if [[ ! -f ${name}.tar.gz ]]; then
  # url="https://gitlab.freedesktop.org/vdpau/${name}.git"
  # echo "git clone --depth 1 ${url}"
  # git clone --depth 1 ${url}

    # Cloning may stall for some reason. Use the zip file instead.
    url="https://github.com/freedesktop/vdpauinfo/archive/refs/heads/master.tar.gz"
    echo "curl -LO ${url}"
    curl -LO ${url}
    mv ${name}-master.tar.gz ${name}.tar.gz
fi

if ! tar tzf ${name}.tar.gz &>/dev/null; then
    echo corrupted archive, skipping...
    exit 1
fi
    tar xzf ${name}.tar.gz

if [[ -d ${name} ]]; then
    cd ${name} || exit $?
    PKG_CONFIG_PATH=/usr/local/lib/pkgconfig ./autogen.sh --prefix=/usr/local && \
    make && make install
fi

