#!/bin/bash

name="dav1d"
branch="1.0.0"
echo "building ${name} branch ${branch}"

mkdir -p builddir && cd builddir || exit $?

builddir="${PWD}"
cleanup(){
cd "${builddir}" ; rm -rf "${name}" && echo -e "\nDirectory cleaned!";
}
trap cleanup EXIT

find . -type f -mtime +1 -exec rm -rf {} \;

if [[ ! -f ${name}.tar.gz ]]; then
    url="https://code.videolan.org/videolan/${name}.git"
    echo "git clone --depth 1 --branch ${branch} ${url}"
    if ! git clone --depth 1 --branch ${branch} ${url}; then
        echo something wrong with git clone, skipping...
        exit 1
    fi
    tar czf ${name}.tar.gz ${name}
else
    tar xzf ${name}.tar.gz
fi

if [[ -d ${name} ]]; then
    mkdir -p ${name}/build && cd ${name}/build || exit $?
    meson setup \
        -Denable_asm=true \
        -Denable_examples=false \
        -Denable_tests=false \
        -Denable_tools=false \
        -Dtestdata_tests=false \
        --buildtype=release .. --prefix=/usr/local --libdir=lib && \
    ninja && ninja install
fi

