#!/bin/env bash

name="fdk-aac"
echo "building ${name}"

mkdir -p builddir && cd builddir || exit $?

builddir="${PWD}"
cleanup(){
cd "${builddir}" || exit $? ; rm -fr "${name}" && echo -e "\nDirectory cleaned!";
}
trap cleanup EXIT

find . -type f -mtime +1 -exec rm -rf {} \;

if [[ ! -f ${name}.tar.gz ]]; then
    url="https://github.com/mstorsjo/${name}"
    echo "git clone --depth 1 ${url}"
    if ! git clone --depth 1 ${url}; then
        echo something wrong with git clone, skipping...
        exit 1
    fi
    tar czf ${name}.tar.gz ${name}
else
    tar xzf ${name}.tar.gz
fi

if [[ -d ${name} ]]; then
    cd ${name} || exit $?
    autoreconf -fiv && \
    ./configure --prefix=/usr/local --enable-shared && \
    make -j"$(nproc)" && make install && \
    rm -f /usr/local/lib/libfdk-aac.la /usr/local/lib/libfdk-aac.a
fi

