#!/bin/env bash

name="vid.stab"
echo "building ${name}"

mkdir -p builddir && cd builddir || exit $?

builddir="${PWD}"
cleanup(){
cd "${builddir}" || exit $? ; rm -fr "${name}" && echo -e "\nDirectory cleaned!";
}
trap cleanup EXIT

find . -type f -mtime +1 -exec rm -rf {} \;

if [[ ! -f ${name}.tar.gz ]]; then
    url="https://github.com/georgmartius/${name}.git"
    echo "git clone --depth 1 ${url}"
    if ! git clone --depth 1 ${url}; then
        echo something wrong with git clone, skipping...
        exit 1
    fi
    tar czf ${name}.tar.gz ${name}
else
    tar xzf ${name}.tar.gz
fi

if [[ -d ${name} ]]; then
    cd ${name} || exit $?
    cmake -B build -G Ninja \
        -DCMAKE_INSTALL_PREFIX=/usr/local \
        -DCMAKE_INSTALL_LIBDIR=lib \
        -DCMAKE_POSITION_INDEPENDENT_CODE=1 \
        -DCMAKE_SKIP_RPATH:BOOL=YES \
        -DCMAKE_BUILD_TYPE=Release . && \
    ninja -C build && ninja -C build install
fi

