#!/bin/env bash

name="vmaf-2.3.1"
echo "building ${name}"

mkdir -p builddir && cd builddir || exit $?

builddir="${PWD}"
cleanup(){
cd "${builddir}" || exit $? ; rm -fr "${name}" && echo -e "\nDirectory cleaned!";
}
trap cleanup EXIT

find . -type f -mtime +1 -exec rm -rf {} \;

if [[ ! -f ${name}.tar.gz ]]; then
    url="https://github.com/Netflix/vmaf/archive/v2.3.1.tar.gz"
    echo "curl -LO ${url}"
    curl -LO ${url}
    mv v2.3.1.tar.gz ${name}.tar.gz
fi
if ! tar tzf ${name}.tar.gz &>/dev/null; then
    echo corrupted archive, skipping...
    exit 1
fi

tar xzf ${name}.tar.gz

if [[ -d ${name} ]]; then
    mkdir -p ${name}/libvmaf/build && cd ${name}/libvmaf/build || exit $?
    meson setup \
        -Denable_tests=false \
        -Denable_docs=false \
        -Ddefault_library=shared \
        -Db_lto=true \
        --buildtype=release .. --prefix=/usr/local --libdir=lib && \
    ninja && ninja install
fi

